export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const DISHES_ROUTE = '/dishes'
export const FAVORITES_ROUTE = '/favorites'
export const ADMIN_PANEL_ROUTE = '/admin'
